services:
  backend:
    image: paullaffitte/baserow-backend:latest
    build:
      context: ..
      dockerfile: ./Dockerfile.backend
    environment:
      ADDITIONAL_APPS: baserow.contrib.personal_accounting

  web-frontend:
    image: paullaffitte/baserow-frontend:latest
    build:
      context: ..
      dockerfile: ./Dockerfile.frontend

  celery:
    image: paullaffitte/baserow-backend:latest

  celery-export-worker:
    image: paullaffitte/baserow-backend:latest

  celery-beat-worker:
    image: paullaffitte/baserow-backend:latest
