# Generated by Django 3.2.13 on 2022-07-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0021_settings_allow_reset_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingReport',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.application')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.application',),
        ),
    ]
